Done HW02
sarff/prjctr-golang_beginning pull request #1
Opened 2024-08-11 12:20 UTC by sarff

Стикнувся з  проблемою використання такої структури []struct:
`type Animal []struct {
	ID     int
	Name   string
	Gender string
	Weight int
	OurNil *int // Вимога задачі використати nil
	Cage        // Так ми розуміємо чи спіймали звіра
}`

Ломає функцію Begin  - не зміг адаптувати

2024-08-11 16:40 UTC, alexandear requested changes
Вийшло щось багато зауважень. В загальному, ти трохи переускладнив домашку, використавши цикли, підключення сторонніх пакетів, рандом, складні if-и. Бажано просто було зробити тими способами, які були вивчені на вебінарах, або були в матеріалах до вебінарів. Але хай вже так буде.

Пропоную доробити трішки.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +	"github.com/brianvoe/gofakeit/v6" // fake data
Ти класно зробив, що додав пакет для роботи з фейками, хоч це не обов'язково було робити. Але є нюанси.

Програма не запускається:
```
❯ cd gocourse02
❯ go run .
```

Так також не працює:
```
❯ go run main.go faker.go
faker.go:4:2: no required module provides package github.com/brianvoe/gofakeit/v6: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

`go` нам підказує, що треба додати `go.mod` файл через команду:

```
❯ go mod init github.com/sarff/prjctr-golang_beginning/gocourse02
```

Та зробити для додавання `go.sum`:
```
❯ go mod tidy
```

Звичайно, закомітити `go.mod` та `go.sum`. Тоді будь-хто, хто склонує собі репу, зможе легко запустити програму без додаткових дій, маючи лише компілятор `go`:

```
❯ cd gocourse02
❯ go run .
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +	"github.com/brianvoe/gofakeit/v6" // fake data
:memo: Другий нюанс, але цей вже мінорний. Бажано використовувати найновішу версію бібліотеки. В дану випадку, найновіша версія gofakeit 7 https://pkg.go.dev/github.com/brianvoe/gofakeit/v7

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +// Функції рандомної генерації
Мені здається, комент зайвий і можна видалити.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	return r.Intn(2) == 1
Можна спростити за допомогою пакету [`math/rand/v2`](https://pkg.go.dev/math/rand/v2):
```suggestion
	return rand.N(2) == 1
```

Ми це не вчили, але просто знай, що бажано використовувати `math/rand/v2` в найновішому Go 1.22.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +func RandInt(min, max int) int {
[`min`](https://pkg.go.dev/builtin#min), [`max`](https://pkg.go.dev/builtin#max) - це вбудовані функції, краще вибрати якесь інше ім'я параметрів

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	AttemptСatchAnimal(*Cage) bool // Сброба зловити звіра в клітку
В назві функції `С` - українська, кирилична. Такого в коді не треба допускати, хіба ти хочеш "насолити" іншим. Тому виправ, будь ласка.

`С` українська та `С` англійська - різні символи, хоч і виглядають однаково. Інші програмісти будуть дуже здивовані, чому вони імплементують метод `AttemptCatchAnimal`, але він не імплементується.

Підозрюю, що поставив кириличну літеру через те, що ти постійно перемикався між українською та англійською розкладками. Пропоную писати коментарі та код в майбутньому виключно англійською. Це міжнародна мова, яку всі програмісти мають розуміти.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +func Reproduction(male, famale *Animal) {
Як думаєш, може краще зробити цей метод властивістю тварини?

Використання буде:

```go
male := Animal{}
female := Animal{}
child := male.Reproduce(female) // or child := female.Reproduce(male)
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	_, err := fmt.Fprintf(os.Stdout, "Replay between %s and %s is complete!! Congratulations to the new animal %v \n", male.Name, famale.Name, *NewAnimals)
Пропоную спростити:
```suggestion
	fmt.Printf("Replay between %s and %s is complete!! Congratulations to the new animal %v \n", male.Name, famale.Name, *NewAnimals)
```

Помилку з [`Printf`](https://pkg.go.dev/fmt#Printf) можна не обробляти. В загальному, ця функція ніколи не повертає помилки. Теоретично це можливо, але ось на практиці дуже рідко таке трапляється.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	NumberOfCaught int
Може так краще? Трохи не зрозуміло, що таке `NumberOfFound`:
```suggestion
	AnimalsFound  int
	AnimalsCaught int
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +func (a *Animal) AttemptСatchAnimal(cage *Cage) bool {
Я не впевнений, що методи `FindEscapedAnimal` та `AttemptCatchAnimal` мають бути прив'язаними до тварини. Бо виходить, що тварина сама себе знаходить і ловить. Може краще зробити ці ж методи, але для наглядача ZooKeeper? Це ж він/вона ловить тварин.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	Cage        // Так ми розуміємо чи спіймали звіра
А може краще зробити поле `Animal *Animal` в структурі клітки `Cage`? `Animal` буде `nil`, якщо клітка пуста.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +func New(zkName string, animNumber int) (*ZooKeeper, *Cage) {
Бажано так не робити. Конструктор зазвичай конструює лише одну структуру за раз. Тобто в нас має бути окремо конструктор для клітки `NewCage`, окремо для тварини `NewAnimal`, окремо для наглядача `NewZooKeeper`. Оцей загальний `New` можна видалити.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +func (k *ZooKeeper) Begin(catch Catcher, cage *Cage) {
Читачу з назви функції має бути зрозумілим, для чого вона. `ZooKeeper.Begin` - не дуже зрозуміло. Чи можемо ми якось переробити або хоча б додати коментар, який описує, що функція робить?

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	//for reproduction:
:memo: В коментах між `//` та першим словом завжди має бути пробіл
```suggestion
	// for reproduction:
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +		_, err := fmt.Fprintf(os.Stdout, "same-sex reproduction is prohibited")
Тут теж, давай краще `fmt.Println` використаємо.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +		animals := &Animal{ID: i + 1, Name: fakeData.Name, Gender: fakeData.Gender, Weight: RandInt(10, 50)}
Зазвичай, суфікс `s` в Go використовується для позначення кількох об'єктів.

`animals` - це кілька тварин
`animal` - лише одна тварина

Тобто, в нашому випадку ми створюємо одну тваринку, краще:

```suggestion
		animal := &Animal{ID: i + 1, Name: fakeData.Name, Gender: fakeData.Gender, Weight: RandInt(10, 50)}
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	_, err := fmt.Fprintf(os.Stdout, "Zookeeper found %d and cought %d animals Out of %d\n", keeper.NumberOfFound, keeper.NumberOfCaught, animalNumber)
Здається, помилка:

`cought` має бути `caught` https://dictionary.cambridge.org/dictionary/english/caught

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	for i, v := range cagedAnimals {
Ми ще не вчили `for`, не обов'язково було ускладнювати собі роботу ;)

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	Gender string
Чи можемо ми створити окремий тип для `Gender` з константами `Male` та `Female`? Думаю, так трішки краще, ніж `string`.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +
Слайси (slices) ми не вчили. Не треба ускладнювати життя. Тобто `type Animal []struct` не потрібно імплементувати.

`cagedAnimals` хай вже буде.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +	// TODO: перевірити чи  правильні тут розрахунки
`TODO` бажано не лишати в коді на рев'ю.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +	Pointer *int
Ці поля ніде не використовуються. Може видалити?

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +type Bar struct {
Здається, теж непотрібна структура

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +	"github.com/brianvoe/gofakeit/v6" // fake data
`gofakeit` дуже класно розкриває суть пакету, комент зайвий:
```suggestion
	"github.com/brianvoe/gofakeit/v6"
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +// Create structs with random injected data
Не впевнений, що структура створює "create". Ми нижче просто декларуємо структуру `Fake`.

2024-08-11 16:40 UTC, alexandear commented on gocourse02/faker.go
> +func GetFaker() Fake {
Може краще перейменувати? Це ж типу конструктор:
```suggestion
func NewFake() Fake {
```

Ще можна додати коментар:

```go
// NewFakes returns Fake filled with random data.
func NewFake() Fake {
```

2024-08-11 16:40 UTC, alexandear commented on gocourse02/main.go
> +const animalNumber = 15 // Кількість звірів які повтікали
Здається, якщо назвати `escapedAnimalsCount`, то можна видалити коментар.

2024-08-11 20:46 UTC, sarff commented on gocourse02/faker.go
> +	"github.com/brianvoe/gofakeit/v6" // fake data
Версію оновив до 7.  По іншому питанню, я правильно  розумію що треба додавати  в git файл go.mod  ? бо в мене  виконується 
```
cd gocourse02
go run .
```

2024-08-12 11:01 UTC, alexandear commented on gocourse02/faker.go
> +	"github.com/brianvoe/gofakeit/v6" // fake data
Так, вже є.

2024-08-12 13:34 UTC, sarff commented on gocourse02/main.go
> +	for i, v := range cagedAnimals {
хай буде)

2024-08-12 13:35 UTC, sarff commented on gocourse02/main.go
> +
таки розібрався як треба зробив через Animal        []Animal

2024-08-12 14:02 UTC, sarff commented on gocourse02/main.go
> +	Gender string
Ось так, але в проект н додаю, тому що це поркиває gofakeit. type Gender string

const (
male   Gender = "male"
female Gender = "female"
)

2024-08-12 15:06 UTC, alexandear requested changes
Закоментованого коду краще уникати. Коментарі - так, код - ні.

Ще бажано умову задачі про `nil` виконати.

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +//)
Здається, потрібно це розкоментувати і змінити поле `Gender` в звіра:

```
type Animal struct {
	// ...
	Gender Gender
	// ..
}
```

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +	fmt.Fprintf(os.Stdout, "Zookeeper found %d and caught %d animals Out of %d\n", keeper.AnimalsFound, keeper.AnimalsCaught, escapedAnimalsCount)
```suggestion
	fmt.Printf("Zookeeper found %d and caught %d animals Out of %d\n", keeper.AnimalsFound, keeper.AnimalsCaught, escapedAnimalsCount)
```

📝 Зазвичай, `fmt.Fprintf(os.Stdout` краще використовувати тоді, коли в нас є вивід в `os.Stderr`. Якщо програма виводить лише в stdout, то можна просто `fmt.Printf`.

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +func (male *Animal) Reproduction(famale *Animal) {
одруківка в назві параметру:
```suggestion
func (male *Animal) Reproduction(female *Animal) {
```

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +
📝 пусті рядки краще не залишати

```suggestion
```

Хоча в реальних проектах за цим зазвичай слідкують лінтери.

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +func NewZooKeeper(zkName string) *ZooKeeper {
Можна перейменувати, бо напевно не буде більше ніяких імен:
```suggestion
func NewZooKeeper(name string) *ZooKeeper {
```

Так, неймінг для Go-програм дуже важливий, тому я придираюсь. Тут можна трішки почитати https://go.dev/doc/effective_go#names

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +func NewAnimal(i int) *Animal {
`i` - це слушна назва для змінної в циклі, але не для конструктора.

Може `id` краще?

```suggestion
func NewAnimal(id int) *Animal {
```

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +	Animal        []Animal
Я правильно розумію, що в одній клітці може бути багато звірів?

Мені здається, що в зоопарках одна клітка - один звір.

Але хай вже буде, якщо така логіка.

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +	//Cage        // Так ми розуміємо чи спіймали звіра
Закоментованого коду бажано уникати. Можемо видалити?

2024-08-12 15:06 UTC, alexandear commented on gocourse02/main.go
> +	OurNil *int // Вимога задачі використати nil
Це поле ніяк не використовується. Може видалити?

2024-08-12 15:06 UTC, alexandear commented on gocourse02/go.mod
> +module prjctr-golang_beginning
Дякую, що додав go.mod/go.sum.

Ось так більш ідіоматично буде:
```suggestion
module github.com/sarff/prjctr-golang_beginning/gocourse02
```

Далі на курсі дізнаємось, чому.

2024-08-12 15:12 UTC, sarff commented on gocourse02/main.go
> +	Animal        []Animal
так початкова ідея була така, зукіпер не може взяти більше однієї клітки і спіймає стільки звірів, скільки дозволить клітка

2024-08-12 15:32 UTC, sarff commented on gocourse02/main.go
> +//)
Так це я зрозумів, як створити свій тип, використати його в структурі і передати в константи. Але далі потрібно написати свою функцію рандому для  NewAnimal, щоб замінити fakeData.Gender або розібратися як це додати до пакету gofakeit. Тому не робив далі - закомінтив. Тому з вашого дозволу просто видалю, щоб не побити рекорд в review на projecti)))

2024-08-13 17:55 UTC, alexandear requested changes
Ще кілька зауважень.

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +//)
Я зробив "Unresolve conversation", бо закоментований код все ще присутній.

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +	NewAnimals := &Animal{ID: escapedAnimalsCount + 1, Name: fakeData.Name, Gender: fakeData.Gender, Weight: avgWeight}
Дрібниця, але все ж:
```suggestion
	newAnimal := &Animal{ID: escapedAnimalsCount + 1, Name: fakeData.Name, Gender: fakeData.Gender, Weight: avgWeight}
```

Можна навіть перейменувати на `young` (чи `child`).

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +	NewAnimals := &Animal{ID: escapedAnimalsCount + 1, Name: fakeData.Name, Gender: fakeData.Gender, Weight: avgWeight}
Такий довгий рядок важко читається і модифікується, бо цілих чотири поля в структурі і всі в один рядок. А що буде, якщо в майбутньому додасться ще одне поле?

Пропоную ось таке форматування:

```suggestion
	child := &Animal{
		ID:     escapedAnimalsCount + 1,
		Name:   fakeData.Name,
		Gender: fakeData.Gender,
		Weight: avgWeight,
	}
```

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +//)
Щодо "рекорд в review" не переживай, такого немає ;)

Кожен мій коментар в PR - це спосіб передати частку знань від мене до тебе.

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +func (k *ZooKeeper) AttemptCatchAnimal(cage *Cage, a *Animal) bool {
Просто для консистентності параметрів:
```suggestion
func (k *ZooKeeper) AttemptCatchAnimal(cage *Cage, animal *Animal) bool {
```

Бо в нас клітка "cage", то й звір вже має бути повністю "animal".

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +	NewAnimals := &Animal{ID: escapedAnimalsCount + 1, Name: fakeData.Name, Gender: fakeData.Gender, Weight: avgWeight}
Спосіб фіксу 2: чи не можемо ми тут використати конструктор? Так, конструктор `NewAnimal` приймає лише параметр `id`. Але ж можна розширити конструктор.

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +}
📝 (це фіксити не обов'язково)

Бажано декларувати конструктори поруч з типами, так легше читається.

2024-08-13 17:55 UTC, alexandear commented on gocourse02/main.go
> +	var male, famale = -1, -1
Одруківка:
```suggestion
	var male, female = -1, -1
```

2024-08-14 10:40 UTC, alexandear requested changes
Ще трохи змін.

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +// Функція розможноження
```suggestion
// Функція розмноження
```

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +}
Підозрюю, що буде працювати без параметру `catch`. Не варто ускладнювати там, де можна не ускладнювати.

```suggestion
func (k *ZooKeeper) SearchingForAnimalsReturnToCage(animal *Animal, cage *Cage) {
	if k.FindEscapedAnimal() {
		k.AnimalsFound++
		if k.AttemptCatchAnimal(cage, animal) {
			k.AnimalsCaught++
			cage.CurrentSeats++
		}
	}
}
```

Звичайно, ще треба не забути поправити цей виклик в `main`.

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +func (k *ZooKeeper) SearchingForAnimalsReturnToCage(catch Catcher, animal *Animal, cage *Cage) {
Думаю, варто перейменувати функцію на `SearchForAnimalAndReturnToCage`. Тому що функція виконує дві дії: шукає одного звіра і садить його в клітку.

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +	return &Cage{numberSeats, maxWeight, 0, 0, animals}
Не варто без особливої потреби ініціалізувати структуру без вказання імен полів. Тому що це гірше читається, гірше розширюється і в майбутньому може стати причиною багів на рівному місці. Краще так:

```suggestion
	return &Cage{
		MaxSeats:      numberSeats,
		MaxWeight:     maxWeight,
		CurrentSeats:  0,
		CurrentWeight: 0,
		Animal:        animals,
	}
```

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +	Animal        []Animal
Рекомендація перейменувати поле: додати суфікс `s` до `Animal`, тому що це поле, де може бути багато звірів.

```suggestion
	Animals       []Animal
```

Я не знайшов формального правила, за яким обов'язково треба додавати `s` до імен слайсів. Але так з мого досвіду всі роблять.

Як аргумент, можу привести код Go для змінних типу слайс стрінгів `[]string` https://github.com/search?q=repo%3Agolang%2Fgo%20%5B%5Dstring%7B&type=code

З пошуку видно, що назви такі:

```
typeFiles
mimeGlobs
platformZoneSources
IllegalPrefixes
logTypes
logPaths
```

Але є й такі:
```
skip
htmlReplacementTable
list
ss
Register
```

Що є виключенням треба дивитись конкретний контекст, чому так назвали.

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +	return &ZooKeeper{name, 0, 0}
Нижче написав, чому так краще:
```suggestion
	return &ZooKeeper{Name: name, AnimalsFound: 0, AnimalsCaught: 0}
```

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +func RandInt(minValue, maxValue int) int {
Неймінг в Go - це окреме мистецтво. Ось тут трохи можна глянути, як ідіоматично називати змінні, пакети, інтерфейси https://go.dev/talks/2014/names.slide#1

Пропоную так перейменувати параметри, можна й коментар додати:
```suggestion
// RandInt generates integer from <low, high> interval.
func RandInt(low, high int) int {
```

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +	child := NewAnimal(escapedAnimalsCount, avgWeight)
Мені та майбутньому читачу (підозрюю) не зовсім зрозуміло, чому `id` дитини має значення `escapedAnimalsCount`. Треба коментар до коду і пояснення під моїм коментом.

А що буде, якщо зміниться значення константи `escapedAnimalsCount` з 15 на 16?

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +	animals := make([]Animal, 0)
Нам відомо кількість звірів в клітці? Якщо так, то можна:
```suggestion
	animals := make([]Animal, 0, animNumber)
```

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +func NewCage(animNumber int) *Cage {
Може так краще? Типу `capacity` - це кількість звірів, які можуть поміститись в клітці:

```suggestion
func NewCage(capacity int) *Cage {
```

2024-08-14 10:40 UTC, alexandear commented on gocourse02/main.go
> +func (male *Animal) Reproduction(female *Animal) {
Я придумав, де можемо використати `nil` в твоїй програмі.

Пропоную зробити так, щоб ця функція повертала дитину `*Animal`. І змоделювати так, що `*Animal` з якоюсь вірогідністю була `nil`. Це щось типу безпліддя.

В `main` додати перевірку `if child == nil` вивести щось типу "Звірі такі-то не змогли народити дитинча", `else` - змогли та інфу про неї.

2024-08-14 10:41 UTC, alexandear commented
Ще бажано проапдейтити "Description" в PR.

2024-08-14 18:57 UTC, sarff commented on gocourse02/main.go
> +	return &ZooKeeper{name, 0, 0}
GoLang IDE рекомендує навіть так: return &ZooKeeper{Name: name} Виходить нульові видатили (але це тільки якщо вони в кінці). Але виправив так як ви вказали, мабуть це біль інформативно

2024-08-14 19:11 UTC, sarff commented on gocourse02/main.go
> +	child := NewAnimal(escapedAnimalsCount, avgWeight)
Функція NewAnimal() повертає  структуру &Animal{ID: id + 1...} тому при зміні константи escapedAnimalsCount завжди child буде +1 (якщо 16 то child буде мати id 17). Чому ID починається не з нуля, мабуть тому що цей неймінг пішов з Баз данних і ID = 0 в базу не можна записати

2024-08-14 19:31 UTC, sarff commented on gocourse02/main.go
> +	animals := make([]Animal, 0)
Зробив так animals := make([]Animal, 0, numberSeats+1). Максимальная кількість звірів яка може поміститися в клітку +1=child

2024-08-14 19:56 UTC, sarff commented
Це не зрозумів де я можу прописати description в PR, бачу тільки коммент

2024-08-14 20:01 UTC, sarff commented
Прибрав catcher, тепер цей інтерфейс незадіяний 
`type Catcher interface {
	FindEscapedAnimal() bool                // Спроба знайти звіра
	AttemptCatchAnimal(*Cage, *Animal) bool // Сброба зловити звіра в клітку
}`

гадаю що ось так буде не дуже:

```
type _ interface {
	FindEscapedAnimal() bool                // Спроба знайти звіра
	AttemptCatchAnimal(*Cage, *Animal) bool // Сброба зловити звіра в клітку
}
```

2024-08-15 10:49 UTC, alexandear approved these changes
LGTM

2024-08-15 10:49 UTC, alexandear commented on gocourse02/main.go
> +}
Можна видалити незадіяний інтерфейс.

2024-08-15 13:41 UTC, merged