Hw03
sarff/prjctr-golang_beginning pull request #2
Opened 2024-08-16 20:48 UTC by sarff

Змінив структуру від початкової в завданні (перевів Movement в слайс  []Movement:
`Rodent struct {
		ID      int
		Type    RodentType
		History []Movement
	}`

Програма  виконує наступне:

- Симулює рух гризуунів
- Зберігає історію руху
- Видаляє, зберігає,  шукає історію  руху
- Звіт де був гризун на початку дня і  де зупинився в кінці дня 
- звіт по сектору в указаний час
- Історія руху через датчик, зберігається в загальній історії

2024-08-18 15:37 UTC, alexandear requested changes

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/go.mod
> +go 1.22.5
Варто використовувати найновішу версію go 1.23.0

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +	ManufacturerDate time.Time
Зазвичай ось так поля називають:
```suggestion
	ManufacturedAt time.Time
```

https://google.github.io/styleguide/go/decisions#repetition

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +		{"Brilinta", fake.DateRange(time.Now().AddDate(-1, 0, 0), time.Now().AddDate(0, 0, 1))},
`time.Now().AddDate(-1, 0, 0)` та `time.Now().AddDate(0, 0, 1))` повторюються 7 разів. Може винести в окремі змінні?

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +
📝 зайвий пустий рядок

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/go.mod
> +module github.com/sarff/prjctr-golang_beginning/gocourse02/drugs_task
Папка називається `gocourse03/drugsTask`, тому і модуль має бути `gocourse03/drugsTask`.

Це тут написано https://go.dev/ref/mod#module-path

```suggestion
module github.com/sarff/prjctr-golang_beginning/gocourse03/drugsTask
```

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/go.mod
> +module github.com/sarff/prjctr-golang_beginning/gocourse02/drugs_task
Те саме стосується `mouseMetropolis`.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +	var sixMonthDrugs = make([]Drugs, 0)
Змінні оголошуються якнайближче до місця їх використання. Тому пропоную перемістити їх нижче, перед циклом `for`.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +	var sixMonthDrugs = make([]Drugs, 0)
Чи можемо ми спростити? Наприклад, ось так `var oldDrugs []Drugs` читається трішки легше, ніж  `var oldDrugs = make([]Drugs, 0)`.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/go.mod
> +module github.com/sarff/prjctr-golang_beginning/gocourse02/drugs_task
Може перейменувати `drugsTask` на просто `drugs`? По суті, у нас кожна директорія є таскою)

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +	fmt.Println(oldDrugs)
Може зробимо трішки інформативніший вивід для користувача?

Бо зараз виглядає ось так, коли запускаю:
```
[]
[{Cyclobenzaprine 2024-02-25 02:35:56.476564505 +0000 UTC} {Brilinta 2024-05-15 02:03:46.355558356 +0000 UTC}]
[{Acetaminophen 2023-10-14 17:18:36.366825857 +0000 UTC} {Lofexidine 2024-01-19 21:38:12.65660171 +0000 UTC} {Pantoprazole 2024-01-30 12:19:38.112986648 +0000 UTC} {Methadone 2023-10-29 19:36:40.671005873 +0000 UTC} {Farxiga 2023-09-29 05:17:52.918954102 +0000 UTC}]
```

Що би хотілось:
- список ліків до сортування
- сьогоднішня дата
- список ліків після сортування: `For use: ...`, `For sale: ...`, `For disposal: ...`

2024-08-18 15:37 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +		case dayDiff < 70:
Краще працювати з місяцями, ніж з днями. 70 і 200 днів - важка для розуміння конструкція.

Ось ці функції мають стати корисними:
- https://pkg.go.dev/time#Time.AddDate
- https://pkg.go.dev/time#Time.After
- https://pkg.go.dev/time#Time.Before

Переглянь документацію, приклади і тоді вдасться переробити код з використанням цих функцій.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +*/
📝  Такі коменти з умовою задачі або описом програми зазвичай додаються перед декларацією `package`.

Приклади:

https://github.com/golang/tools/blob/master/cmd/bisect/main.go#L5
https://github.com/golang/tools/blob/master/cmd/bundle/main.go#L5

2024-08-18 15:37 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	sensor      Sector     = "sensor"
Невже сенсор є сектором? Якось дивно.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +const (
Різні типи і групи констант зазвичай розділяються пустим рядком.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	}
Чи можемо ми обійтися без `else`? Я думаю, що можемо.

2024-08-18 15:37 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	return n
📝 може в один рядок?

2024-08-18 15:37 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	var rodents []Rodent
Пропоную оголосити структуру `MiceRoom`, в якій буде поле `rodents []Rodent`. Далі можемо вже реалізувати функції пошуку, видалення, додавання з цим слайсом.

Бо в теперішній реалізації метод "findHistory" нічого не шукає.

2024-08-18 19:03 UTC, sarff commented on gocourse03/mouseMetropolis/main.go
> +	sensor      Sector     = "sensor"
виходить "через датчик"  - мається на увазі "шляхом використання датчику", я подумав що цей датчик ще стоїть десь в середині. Тоді просто видаляю sensor з констант

2024-08-19 13:10 UTC, alexandear requested changes

2024-08-19 13:10 UTC, alexandear commented on gocourse03/drugs/main.go
> +	dateRangeTo := time.Now().AddDate(0, 0, 1)
Я би ось так назвав змінні:
```suggestion
	fakeStart := time.Now().AddDate(-2, 0, 0)
	fakeEnd := time.Now().AddDate(0, 0, 1)
```


https://pkg.go.dev/github.com/brianvoe/gofakeit#DateRange
```
func DateRange(start, end time.Time) time.Time
```

2024-08-19 13:10 UTC, alexandear commented on gocourse03/drugs/main.go
> +	var sixMonthDrugs = make([]Drugs, 0)
Здається, я вже коментив про це спрощення:
```suggestion
	var oldDrugs []Drugs
	var newDrugs []Drugs
	var sixMonthDrugs []Drugs
```

В реальному коді зустрічається більше мій варіант, ніж `make` з `0`.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/drugs/main.go
> +	fmt.Println("Today's date: ", time.Now())
Може зробити змінну для теперішнього часу `now := time.Now()`? `time.Now()` зустрічається 5 разів в коді.

І ще один прикол в тому, що `time.Now()` в цьому рядку - це не той же `time.Now()` в рядку 22. Бо програма виконується - час іде. Щоб зафіксувати поточний час для функції `main`, оголошують змінну.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	return &Rodent{ID: id + 1, Type: typeRodent, History: nil}
Не зовсім зрозуміло, чому `id + 1`? Треба пояснення в коменті над цим, бо підозрюю, що таке ж питання виникне в будь-якого читача коду.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +func (m *MiceRoom) findHistory(ID int) {
Назви змінних в параметрах завжди з маленької літери починаються:
```suggestion
func (m *MiceRoom) findHistory(id int) {
```

Це можна взяти собі на замітку.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +func returnRandSector(from Sector) Sector {
`returnRandSector` не найкраща назва для функції, тому що практично кожна функція щось `return`ить.

Може `randSectorExcluding`? Тоді й `from` перейменувати на `exclude`.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	sector5 Sector = "sector5"
📝 Є варіант перейменувати на `sectorA`, `sectorB`, `sectorC`, тощо. Це легше сприйматиметься за `sector1`, `sector2`.

Комент опціональний.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +func newRodent(id int) *Rodent {
можемо додати комент, що цей конструктор рандомно заповнює тип? Або додати параметр `rodentType rodentType` і рандомізувати тип в `main()`.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +func (r *Rodent) addHistory(movement Movement) {
`addHistory` додає `Movement`, а не `History`. Може перейменувати метод?

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +func (r *Rodent) addHistory(movement Movement) {
Те саме стосується `delHistory`

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +				fmt.Println("time found and successfully deleted: ", m)
Можемо переробити так, що функція повертатиме `true`, якщо видалено і `false`  - якщо не знайдено? Тоді цей `fmt.Println` стане непотрібним тут.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +			fmt.Println("move history: ", rodent.History)
Функції з префіксом `find`, `get` зазвичай щось повертають. Можемо доробити, щоб ця функція повертала історію? І цей `fmt.Println` перемістити вище в `main`.

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +		}
Можемо обійтись без `else`?

2024-08-19 13:10 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +func main() {
Не зовсім дружелюбний вивід програми для користувача. Важко зрозуміти, що відбувається:
```
❯ cd mouseMetropolis
❯ go run .
[{1 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector3]} {2024-08-19 17:00:00 +0300 EEST [sector3 sector5]}]} {2 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector3]} {2024-08-19 17:00:00 +0300 EEST [sector3 sector5]} {2024-08-19 18:00:00 +0300 EEST [sector5 sector3]} {2024-08-19 19:00:00 +0300 EEST [sector3 sector2]} {2024-08-19 20:00:00 +0300 EEST [sector2 sector1]} {2024-08-19 21:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 22:00:00 +0300 EEST [sector2 sector1]} {2024-08-19 23:00:00 +0300 EEST [sector1 sector2]}]} {3 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector3]} {2024-08-19 17:00:00 +0300 EEST [sector3 sector2]} {2024-08-19 18:00:00 +0300 EEST [sector2 sector4]} {2024-08-19 19:00:00 +0300 EEST [sector4 sector5]}]} {4 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 17:00:00 +0300 EEST [sector2 sector3]} {2024-08-19 18:00:00 +0300 EEST [sector3 sector4]} {2024-08-19 19:00:00 +0300 EEST [sector4 sector5]} {2024-08-19 20:00:00 +0300 EEST [sector5 sector2]} {2024-08-19 21:00:00 +0300 EEST [sector2 sector5]} {2024-08-19 22:00:00 +0300 EEST [sector5 sector4]}]} {5 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector4]} {2024-08-19 17:00:00 +0300 EEST [sector4 sector3]} {2024-08-19 18:00:00 +0300 EEST [sector3 sector5]} {2024-08-19 19:00:00 +0300 EEST [sector5 sector4]}]} {6 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector3]} {2024-08-19 17:00:00 +0300 EEST [sector3 sector4]} {2024-08-19 18:00:00 +0300 EEST [sector4 sector2]} {2024-08-19 19:00:00 +0300 EEST [sector2 sector1]} {2024-08-19 20:00:00 +0300 EEST [sector1 sector5]} {2024-08-19 21:00:00 +0300 EEST [sector5 sector1]} {2024-08-19 22:00:00 +0300 EEST [sector1 sector5]}]} {7 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector4]} {2024-08-19 17:00:00 +0300 EEST [sector4 sector2]} {2024-08-19 18:00:00 +0300 EEST [sector2 sector1]} {2024-08-19 19:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 20:00:00 +0300 EEST [sector2 sector1]} {2024-08-19 21:00:00 +0300 EEST [sector1 sector4]} {2024-08-19 22:00:00 +0300 EEST [sector4 sector3]} {2024-08-19 23:00:00 +0300 EEST [sector3 sector5]}]} {8 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector5]} {2024-08-19 17:00:00 +0300 EEST [sector5 sector1]} {2024-08-19 18:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 19:00:00 +0300 EEST [sector2 sector5]} {2024-08-19 20:00:00 +0300 EEST [sector5 sector2]} {2024-08-19 21:00:00 +0300 EEST [sector2 sector3]} {2024-08-19 22:00:00 +0300 EEST [sector3 sector4]}]} {9 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 17:00:00 +0300 EEST [sector2 sector3]} {2024-08-19 18:00:00 +0300 EEST [sector3 sector4]} {2024-08-19 19:00:00 +0300 EEST [sector4 sector5]} {2024-08-19 20:00:00 +0300 EEST [sector5 sector2]}]} {10 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector5]} {2024-08-19 17:00:00 +0300 EEST [sector5 sector4]} {2024-08-19 18:00:00 +0300 EEST [sector4 sector5]} {2024-08-19 19:00:00 +0300 EEST [sector5 sector2]}]} {11 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector3]} {2024-08-19 17:00:00 +0300 EEST [sector3 sector4]} {2024-08-19 18:00:00 +0300 EEST [sector4 sector3]}]} {12 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 17:00:00 +0300 EEST [sector2 sector4]} {2024-08-19 18:00:00 +0300 EEST [sector4 sector5]} {2024-08-19 19:00:00 +0300 EEST [sector5 sector1]} {2024-08-19 20:00:00 +0300 EEST [sector1 sector2]}]} {13 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector4]}]} {14 rat [{2024-08-19 16:00:00 +0300 EEST [sector1 sector4]} {2024-08-19 17:00:00 +0300 EEST [sector4 sector2]} {2024-08-19 18:00:00 +0300 EEST [sector2 sector5]} {2024-08-19 19:00:00 +0300 EEST [sector5 sector4]} {2024-08-19 20:00:00 +0300 EEST [sector4 sector2]} {2024-08-19 21:00:00 +0300 EEST [sector2 sector1]} {2024-08-19 22:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 23:00:00 +0300 EEST [sector2 sector5]} {2024-08-20 00:00:00 +0300 EEST [sector5 sector3]}]} {15 mouse [{2024-08-19 16:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 17:00:00 +0300 EEST [sector2 sector4]} {2024-08-19 18:00:00 +0300 EEST [sector4 sector3]} {2024-08-19 19:00:00 +0300 EEST [sector3 sector5]} {2024-08-19 20:00:00 +0300 EEST [sector5 sector1]} {2024-08-19 21:00:00 +0300 EEST [sector1 sector4]} {2024-08-19 22:00:00 +0300 EEST [sector4 sector1]}]}]
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector3 sector5]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector3 sector5]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector3 sector2]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector2 sector3]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector4 sector3]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector3 sector4]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector4 sector2]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector5 sector1]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector2 sector3]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector5 sector4]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector3 sector4]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector2 sector4]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector4 sector2]}
time found and successfully deleted:  {2024-08-19 17:00:00 +0300 EEST [sector2 sector4]}
move history:  [{2024-08-19 16:00:00 +0300 EEST [sector1 sector2]} {2024-08-19 18:00:00 +0300 EEST [sector3 sector4]} {2024-08-19 19:00:00 +0300 EEST [sector4 sector5]} {2024-08-19 20:00:00 +0300 EEST [sector5 sector2]} {2024-08-19 21:00:00 +0300 EEST [sector2 sector5]} {2024-08-19 22:00:00 +0300 EEST [sector5 sector4]} {2024-08-19 22:00:00 +0300 EEST [sector5 sector4]}]
Start Sector: sector1 || Finish Sector:  sector4
the following rodentsID were in the sector1 at the time 2024-08-19 18:00:00 +0300 EEST: [8]                                                                 
```

Варто трохи переглянути, що та як виводиться.

2024-08-19 15:05 UTC, sarff commented on gocourse03/mouseMetropolis/main.go
> +		}
якщо ми приберемо else  і винесемо до if - то буде помилка індексу, тому я виніс тільки "to"

2024-08-20 05:38 UTC, sarff commented on gocourse03/mouseMetropolis/main.go
> +func main() {
Move history for ID 4 :
-->   2024-08-20 10:00:00 +0300 EEST : [[sectorE sectorC]]
-->   2024-08-20 11:00:00 +0300 EEST : [[sectorC sectorE]]
-->   2024-08-20 08:00:00 +0300 EEST : [[sectorA sectorD]]
-->   2024-08-20 09:00:00 +0300 EEST : [[sectorD sectorE]]
Start and Finish sectors for RodentID: 4
Start Sector: sectorA
Finish Sector:  sectorE
The following rodentsID were in the sectorA at the time 2024-08-20 10:00:00 +0300 EEST: [6 9 11]
All entries with `2024-08-20 09:00:00 +0300 EEST` time are deleted

2024-08-21 16:48 UTC, alexandear approved these changes
LGTM

2024-08-21 16:48 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	report := make([]int, 0)
Здається, я вже коментував про декларацію слайсів:
```suggestion
	var report []int
```

2024-08-21 16:48 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	// make +1 because the ID cannot be 0
Хм, а чому ID не може бути 0?

Якщо я спробую передати -1 в `newRodent(-1)`, що буде?

2024-08-21 16:48 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +				delStatus = true
Чи можемо відразу зробити `return true`? Функція працюватиме коректно після зміни?

2024-08-21 16:48 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +		}
Так працюватиме?
```suggestion
		from = sectorA
		if r.History != nil {
			from = r.History[len(r.History)-1].FromTo[1]
		}
```

Трішки простіше.

2024-08-21 16:48 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +	}
Використання fake якось дуже ускладнює код. Можна за допомогою math/rand/v2:
```suggestion
	sectors := [...]Sector{sectorA, sectorB, sectorC, sectorD}
	randSector := Sector(sectors[rand.IntN(len(sectors))])
	if randSector != exclude {
		return randSector
	}
```

2024-08-21 16:49 UTC, alexandear commented on gocourse03/mouseMetropolis/main.go
> +		}
нижче відписав.

2024-08-21 17:05 UTC, sarff commented on gocourse03/mouseMetropolis/main.go
> +	// make +1 because the ID cannot be 0
у даному випадку нічого, але якщо ми перейдемо на БД, в базу таке не має залетіти... але я не перевіряв. Прибрав +1

2024-08-21 17:14 UTC, merged