Hw04
sarff/prjctr-golang_beginning pull request #3
Opened 2024-08-21 06:07 UTC by sarff

Маємо дві таски з GoDev:
/gocourse04/ExerciseErrorsFromGoDev/
/gocourse04/WordCountFromGoDev/

Одну таску з вебінару:
/gocourse04/viaZoomTask/

Домашня робота:
/gocourse04/SmartZoo/

В домашній роботі стикнувся з складною структурою (вона звісно не є оптимальною для завдання), але так навіть цікавіше - розібратися в складній структурі. Тому тут явно написаний дуже дикий не оптимальний код - але працює) Чекаю багато ревьюшек і переробок)
Реалізував  функції пошуку тварини за імʼям (Lookup), Переміщення тварини  із загону в загін (Migration), Годування тварин, цілого загону (Feeding),  Чистка однієї тварини (Cleaning), Видалення тварини (delAnimal). Допоміжна функція delOldRecord яка перезаписує сектор після переміщення тварин. + Тести і Бенчмарк.

2024-08-21 21:18 UTC, alexandear requested changes

2024-08-21 21:18 UTC, alexandear commented on gocourse03/drugsTask/main.go
> +package main
Помилково закомічено папку `gocourse03`. Підозрюю, що треба видалити з цього PR.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/ExerciseErrorsFromGoDev/main.go
> +}
`When` можна видалити, не потрібна інфа.

Тоді залишиться:
```go
type ErrNegativeSqrt struct {
	What float64
}
```

Яке можна спростити:
```go
type ErrNegativeSqrt float64
```

Функцію `Error() string` самому підправити.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +// Returns the found animal and in which sector and area it is
Можу підказати, що ось так коменти до експортованих методів пишуться:
```suggestion
// Lookup returns the found animal and in which sector and area it is.
```

Почитати про це ось тут https://go.dev/doc/comment

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	if animal != nil {
А чому перевіряється три рази `if animal != nil`, якщо значення `animal` не змінюється між цими перевірками?

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) Feeding(fromaArea, fromSector string) error {
Може назву краще `FeedAnimals`?

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) Feeding(fromaArea, fromSector string) error {
помилка `fromaArea` -> `fromArea`

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	} else {
Можемо обійтися без `else`, використовуючи паттерн "return early"? https://danp.net/posts/reducing-go-nesting/

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) delAnimal(ID int) string {
`ID` -> `id`, бо параметри функції/метода завжди з маленької літери

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	Animals []Animal
В цій домашці можна використовувати лише мапи ;)

Слайси були в попередній.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	return &Zoo{Areas: AreasData}
Краще передавати `areas` як параметр конструктора. Чому? Тому що може бути кілька зоопарків в різних містах, які матимуть різні дані.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	sectorClean := 6
Може оголосити константи для цих значень?

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (a Animal) Cleaning(fromArea string, sectorID int, z Zoo) {
Назви функцій зазвичай дієслова в формі інфінітив, а не герундій (закінчення -ing): `Read`, `Close`, `Finish`, `Clean`, `Write`, `Delete`.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) delOldRecord(fromAreaName string, fromSectorID int, animal Animal) {
`del` -> `delete`

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +)
Краще не оголошувати глобальні змінні для тестів, бо з ними є проблеми. Просто скопіюй в кожен тест оці змінні.

Тест кейси зверху нехай поки лишаються.

В Go є можливість запускати тести паралельно через `t.Parallel()` https://pkg.go.dev/testing#T.Parallel. Але якщо тести використовуватимуть глобальні змінні, то будуть незрозумілі баги.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		t.Errorf("Did not pass the check! Expected: %s Received : %s", testName, animal.Name)
Уяви, що тест зафейлився. Чи зможе стороння людина з цього повідомлення зрозуміти, що трапилось?

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		t.Errorf("Did not pass the check! Expected: %s Received : %s", testName, animal.Name)
Що буде, якщо `animal == nil`?

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +func deepEqual(x, y any) bool {
Ця функція не потрібна, тому що можна ж напряму використовувати `reflect.DeepEqual`.

Ось приклади: https://sourcegraph.com/search?q=context:global+reflect.DeepEqual+path:_test.go+language:Go&patternType=keyword&sm=0

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		testZoo.delAnimal(n + 1)
Не впевнений, що маємо передавати в `delAnimal` параметр `n`.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) delAnimal(ID int) string {
`del` -> `delete`

2024-08-21 21:18 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +					return fmt.Sprintf("time found and successfully deleted: %s", animal.Name)
Може краще просто повертати `true`, якщо знайдено і видалено успішно? А друкувати вже в місці, в якому викликається `delAnimal`.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/WordCountFromGoDev/main.go
> +	separateWord := strings.Fields(s)
`strings.Fields` повертає слайс https://pkg.go.dev/strings#Fields

Тому треба придумати кращу назву для змінної.

2024-08-21 21:18 UTC, alexandear commented on gocourse04/viaZoomTask/main.go
> +	}
Можемо створити ліки з різними датами викоговлення, щоб ліки попадали в різні категорії при сортуванні?

2024-08-22 05:29 UTC, sarff commented on gocourse04/SmartZoo/main.go
> +	Animals []Animal
Структуру взяв з ДЗ (така була умова), треба тоді для наступних курсів виправити). Цього разу вирішив НЕ змінювати структуру взагалі (ніби ситуація що я дороблюю чужий код, і вже структура стала) - тому тут слайси які добряче винесли мені мозок в цій ДЗ)

2024-08-22 13:22 UTC, sarff commented on gocourse04/SmartZoo/main_test.go
> +		testZoo.delAnimal(n + 1)
прошу це перевірити, бо реалізував так: 
```	var (
testZoo     = &Zoo{Areas: tests}
idForDelete int
)

	for n := 0; n < b.N; n++ {
		testZoo.deleteAnimal(idForDelete)
	}```

2024-08-23 20:51 UTC, alexandear requested changes

2024-08-23 20:51 UTC, alexandear commented on gocourse04/ExerciseErrorsFromGoDev/main.go
> +	return 0, nil
Функція виводитиме завжди 0, якщо число невід'ємне?

`Sqrt` - це ж корінь квадратний, `Sqrt(9) == 3`

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	Animals []Animal
Добре. Дякую за пояснення.

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func NewZoo(areasData map[string]Area) *Zoo {
Можна просто `areas`, так коротко та зрозуміло:
```suggestion
func NewZoo(areas map[string]Area) *Zoo {
```

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) Migration(fromAreaName, toArea string, fromSectorID, toSector int, animal Animal) error {
Назви краще робити консистентними.

Якщо у нас `fromAreaName`, то має бути `toAreaName`. Якщо `fromSectorID`, то `toSectorID`.

```suggestion
func (z *Zoo) Migration(fromAreaName, toAreaName string, fromSectorID, toSectorID int, animal Animal) error {
```

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	}
Спробуй, ось так має працювати та робити те саме:
```suggestion
	diningRoom.Animals = append(diningRoom.Animals, val.Animals...)
```

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	return fmt.Errorf("sector not found")
```suggestion
	return errors.New("sector not found")
```

`fmt.Errorf` - це якщо треба щось додати до меседжа помилки

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +func TestCleaning(t *testing.T) {
Цей тест для функції `Clean`, значить і назва має бути відповідна - `TestClean`.

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +func BenchmarkDelAnimal(b *testing.B) {
має ж бути `BenchmarkDeleteAnimal`

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		t.Errorf("Output \n%v not equal to expected \n%v", testZoo, testCleaning)
Надто багато префіксу `test` в назвах змінних. Треба щось з цим зробити. Думаю, варто просто прибрати `test`.

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		t.Errorf("Output \n%v not equal to expected \n%v", testZoo, testCleaning)
комент стосується всіх тестів

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +						 but we got an object with the name %s`, testName, animal.Name)
Здається, задовге повідомлення.

Ось тут можна підглянути https://go.dev/wiki/CodeReviewComments#useful-test-failures і трішки скоротити його.

2024-08-23 20:51 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +var tests = map[string]Area{
Можемо перейменувати всі глобальні змінні в цьому файлі?

`tests` -> `lookupAreas`, бо використовується в `TestLookup`

2024-08-23 20:51 UTC, alexandear commented on gocourse04/WordCountFromGoDev/main.go
> +	splitWords := strings.Fields(s)
Можна ще коротше:
```suggestion
	words := strings.Fields(s)
```

2024-08-25 13:09 UTC, alexandear requested changes

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +func (z *Zoo) Migration(fromAreaName, toAreaName string, fromSectorID, toSectorID int, animal Animal) error {
Можна перейменувати трохи функцію, і комент стане непотрібним:
```suggestion
func (z *Zoo) MoveAnimal(fromAreaName, toAreaName string, fromSectorID, toSectorID int, animal Animal) error {
```

2024-08-25 13:09 UTC, alexandear commented on gocourse04/ExerciseErrorsFromGoDev/main.go
В Go не прийнято `CamelCase` для назв директорій. Назви директорій підпорядковуються тим же правилам, що й назви пакетів, і про це описано тут https://go.dev/blog/package-names

Тому пропоную покращити назви:

```
ExerciseErrorsFromGoDev -> errors
SmartZoo -> smartzoo
WordCountFromGoDev -> wordcount
viaZoomTask -> webinar
```

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	sectorClean = 6
Це дві різні константи, тому краще їх розділяти порожнім рядком

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	sectorClean = 6
Чи треба нам додати константу для area "Techroom" та sector "Dining room"?

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	fmt.Println("Array after deletion:", zooAreas)
Зараз цей рядок виводить "Array":
```
Array after deletion: map[Birds:{birds map[Doves:{3 [{7 Dove1} {8 Dove2} {9 Dove3}]} Hawks:{4 [{11 Hawk2}]}]} Hoofed:{hoofed map[Cows:{0 []} Horses:{1 [{1 Horse1} {2 Horse2} {3 Horse3}]}]} Techroom:{tech room map[Bath room:{6 [{14 Cow4}]} Dining room:{5 [{13 Hawk4} {12 Hawk3} {4 Cow1} {5 Cow2} {6 Cow3}]}]}]
```

Але це ж не масив, а мапа.

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	zooAreas := zoo.Areas
Думаю, що ця змінна не потрібна. Можна скрізь використовувати `zoo.Areas`.

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +	animalName := "Hawk3"
Може так краще?
```suggestion
	const animalName = "Hawk3"
```

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +		fmt.Println("The animals are eating")
Можна ще уточнити, які саме тварини їдять.

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +		fmt.Println("Found and successfully deleted")
Можна ще уточнити, тварина з якою id була видаленою.

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main.go
> +		fmt.Println("The array after the Migration: ", zooAreas)
Але ж `zoo.Areas` - це не `array`

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		Zoo      = &Zoo{Areas: lookupAreas}
`zoo` з маленької, оскільки це локальна змінна. В Slack детально пояснював це https://golang-beginning-6.slack.com/archives/C07FYL62R9C/p1724249714144769

---

*Питання. З якої літери починаються ідентифікатори (назви локальних змінних, констант, глобальних змінних, функцій, типів)?*
Відповідь: з малої, а якщо потрібен експорт - з великої.

В Go, на відміну від більшості мов, має значення, з якої літери починається ідентифікатор. Якщо з малої - ідентифікатор доступний лише всередині пакету. Якщо з великої - змінна/тип/функція/константа/тощо доступні для використання в інших пакетах, тобто експортовані. В залежності від того, треба експортувати чи ні, пишемо ідентифікатор з великої чи малої. https://go.dev/ref/spec#Exported_identifiers За замовчуванням, нічого не треба експортувати (інкапсуляція). Тому за замовчуванням з малої.

Параметри функцій, локальні константи/змінні/функції неможливо експортувати. Тому вони завжди починаються з малої. Ресівери - це ті ж самі параметри функції, тому теж завжди з малої.

Так, інколи зустрічаються локальні константи з великої літери. Це винятки з правил для значного підвищення читабельності.

Уявіть собі таку структуру:
```go
type Animal struct {
    Type string
}
```
Як зробити поле неекспортованим, якщо наступний код не компілюється?

```go
type Animal struct {
    type string
}
```
З назвою поля ”type” ніяк, бо це зарезервований ідентифікатор https://go.dev/ref/spec#Predeclared_identifiers. Придумати іншу назву, наприклад, “animalType”.

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		Zoo      = &Zoo{Areas: lookupAreas}
Коментар стосується до всіх локальних змінних в цьому файлі.

2024-08-25 13:09 UTC, alexandear commented on gocourse04/SmartZoo/main_test.go
> +		t.Errorf("Output \n%v not equal to expected \n%v", testZoo, testCleaning)
Префікс `test` все ще присутній в назвах змінних, тому зробив "Unresolve": `testsCleaning`, `testsMigrated`, `testZoo`, `testMigrated`.

Прошу це виправити, щоб код став трішки читабельніше.

2024-08-27 12:28 UTC, alexandear requested changes

2024-08-27 12:28 UTC, alexandear commented on gocourse04/smartzoo/main_test.go
> +	Animal.Clean(AnimalArea.Name, AnimalSector.ID, *zoo)
Локальні змінні завжди lowercase:
```suggestion
	area, sector, animal := zoo.Lookup(name)
	animal.Clean(area.Name, sector.ID, *zoo)
```

2024-08-27 12:28 UTC, alexandear commented on gocourse04/smartzoo/main_test.go
> +	Animal.Clean(AnimalArea.Name, AnimalSector.ID, *zoo)
Бажано виправити тут та нижче

2024-08-27 12:28 UTC, alexandear commented on gocourse04/smartzoo/main_test.go
> +		zoo.deleteAnimal(idForDelete)
Не впевнений, що цей бенчмарк правильний.

Go запускає `zoo.deleteAnimal(0)` N разів.

Після першого разу видалиться звір 0, а далі цього звіра вже не буде. Тобто бенчмарк для першого запуску і для N-го відрізнається.

Рекомендую почитати https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go та спробувати виправити, щоб бенчмарк був більш точним.

2024-08-27 12:28 UTC, alexandear commented on gocourse04/smartzoo/main_test.go
> +var testsCleaning = map[string]Area{
```suggestion
var cleanAreas = map[string]Area{
```

2024-08-27 12:28 UTC, alexandear commented on gocourse04/smartzoo/main_test.go
> +var testsMigrated = map[string]Area{
```suggestion
var migrateAreas = map[string]Area{
```

2024-08-27 19:24 UTC, sarff commented on gocourse04/smartzoo/main_test.go
> +		zoo.deleteAnimal(idForDelete)
тоді виходить що ця функція не підходить для бенчмарка. Зробив дві інші функції

2024-08-27 20:14 UTC, alexandear approved these changes
LGTM

2024-08-27 20:14 UTC, alexandear commented on gocourse04/smartzoo/main_test.go
> +func BenchmarkClean(b *testing.B) {
Здається, з `animal.Clean` та сама проблема, що й була з `deleteAnimal` https://github.com/sarff/prjctr-golang_beginning/pull/3#discussion_r1732753820

2024-08-28 16:07 UTC, sarff commented on gocourse04/smartzoo/main_test.go
> +func BenchmarkClean(b *testing.B) {
ні, тому що функція повертає звірів в сектор з якого вони прийшли. Тому вони будуть ходити і повертатись завжди

2024-08-28 16:16 UTC, merged