Hw05
sarff/prjctr-golang_beginning pull request #4
Opened 2024-08-25 08:53 UTC by sarff

**Папка ZoomTask** - те що було в зумі, але умовно просто розібрав приклад (який писав Евген) і трохи змінив для кращого розуміння

**Папрка HW05 - Домашка**
Функція Move() імітує рух тварини і запускає основний алгоритм: 1) Робимо скріншот з камери TakeScreenshot() 2) Зберігаємо на наш сервер в слайс SaveToServer()

Зробив один тест на функцію SaveToServer() з обробкою panic, для тесту panic треба розкоментувати : 
```   
        //enable for test panic in test
	//var p *string
	//fmt.Println(*p)
```

2024-08-25 13:37 UTC, alexandear requested changes

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
Пропоную покращити назви папок, писав тут https://github.com/sarff/prjctr-golang_beginning/pull/3#discussion_r1730330182

```
HW05 -> zooobservation
ZoomTask -> webinar
```

2024-08-25 13:37 UTC, alexandear commented on gocourse05/ZoomTask/main.go
> +	var png = PNGImageProcessor{
Так простіше:
```suggestion
	bmp := BMPImageProcessor{
		path: "./image/image.bmp",
	}
	png := PNGImageProcessor{
```

Знову ж таки, ось це можна відформатувати автоматично за допомогою `gofumpt`. Писав про це в Slack https://golang-beginning-6.slack.com/archives/C07EVP8S4FK/p1724071944955179

---
Не забувайте видаляти непотрібні пусті рядки, як ось тут:
```
func sum(a, b int) int {

	return a + b
}
```
`gofmt` таке пропускає, а я - ні.  В реальних проектах на десятки тисяч рядків, зайвих рядків може бути тисячу, а це вже немало. Наприклад, ось мій PR, де видалялись непотрібні рядки, його без проблем прийняли.

Щоб полегшити собі життя, варто поставити `gofumpt` https://github.com/mvdan/gofumpt. Цей тул є надбудовою над gofmt: видаляє непотрібні пусті рядки, сортує імпорти тощо. В README вказано точніше, що програма вміє робити.

Поставити такою командою:
```
go install mvdan.cc/gofumpt@latest
```

Щоб відформатувати всі файли:
```
gofumpt -w .
```

Також можна запускати ось так, якщо з якоїсь причини не працює попередня команда:
```
go run mvdan.cc/gofumpt@latest -w .
```

2024-08-25 13:37 UTC, alexandear commented on gocourse05/ZoomTask/main.go
> +		err = p.Process()
Якщо змінити ось так
```suggestion
		err := p.Process()
```
то рядок `err := error(nil)` можна видалити. Спробуй.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/ZoomTask/main.go
> +		err = p.Process()
Зазвичай завжди пишуть `var err error` замість `err := error(nil)`, якщо треба оголосити змінну типу `error`.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/ZoomTask/main.go
> +			return
Напевно, має бути якийсь `fmt.Println(err)`

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main_test.go
> +	err = testDayCam.SaveToServer("left", testHistory, 1)
```suggestion
	err := testDayCam.SaveToServer("left", testHistory, 1)
```
і можна видалити `err := error(nil)` вище

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main_test.go
> +	testHistory := &History{{
Префікс `test` не потрібно додавати в назвах змінних, бо це зайва інформація. Всі змінні в цьому файлі `main_test.go` стосуються тестів. І немає такого правила і не може бути, що треба додавати `test-` в назву змінної.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main_test.go
> +	testHistory := &History{{
Писав про це тут https://github.com/sarff/prjctr-golang_beginning/pull/3#discussion_r1729499585

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +	cam NightCamera
Чому `ID` експортоване поле, а `cam` - неекпортоване?

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +	dayCam := DayCamera{
Не потрібно скорочувати `camera` до `cam`. Це не таке вже й довге слово
```suggestion
	dayCamera := DayCamera{
```

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +	dayCam := DayCamera{
Комент стосується всіх змінних `cam` в PR.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +
Зайвий пустий рядок.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +}
Ці два методи не покриті тестами.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +}
Це два методи не покриті тестами.

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +}
Зараз зроблено так, що тигр сам себе фоткає на денну камеру. Не думаю, що в структуру тигра запихувати камеру. Він же лише рухається, судячи з умови задачі "Даними може виступати рух певної тварини. Наприклад: тигр, пішов ліворуч; ведмідь, стоїть".

2024-08-25 13:37 UTC, alexandear commented on gocourse05/HW05/main.go
> +	//fmt.Println(*p)
Закоментований код не можна залишати в коміті. Це перше правило.

Друге правило, щоб змінити якусь поведінку в тестах, не потрібно щось робити з продакшен кодом.

Паніку можна викликати, якщо просто передати `nil` як параметр `history`.

2024-08-31 07:51 UTC, sarff commented on gocourse05/ZoomTask/main.go
> +	var png = PNGImageProcessor{
не розумію чому в мене не працює після заміни ноута, буду розбиратись

2024-09-02 10:34 UTC, alexandear requested changes

2024-09-02 10:34 UTC, alexandear commented on gocourse05/webinar/main.go
> +func (i *PNGImageProcessor) Process() error {
`i` не дуже вдала назва для ресівера, тому що велика вірогідність колізії з `i` в циклах.

Краще `p`, від `processor`.

2024-09-02 10:34 UTC, alexandear commented on gocourse05/webinar/main.go
> +	fmt.Println(*s)
Додай, будь ласка, коментар, що тут симулюється паніка.

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +	direct := [...]Direction{left, right, top, bottom}
Може так?
```suggestion
	directions := [...]Direction{left, right, top, bottom}
```

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +	for i := 0; i < 10; i++ {
Сучасний Go:
```suggestion
	for range 10 {
```

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +	cam     Camera
Можна не скорочувати:
```suggestion
	camera  Camera
```

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +func (d *DayCamera) DetectMovement(direction Direction, history *History, animalID int) error {
Можемо ось так зробити?
```suggestion
func (d *DayCamera) DetectMovement(direction Direction, historyItems []HistoryItem, animalID int) ([]HistoryItem, error) {
```

Ось як тут https://go.dev/wiki/SliceTricks#move-to-front-or-prepend-if-not-present-in-place-if-possible:
```go
// moveToFront moves needle to the front of haystack, in place if possible.
func moveToFront(needle string, haystack []string) []string {
```

Це такий паттерн, щоб додавати елементи в слайс.

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	err := error(nil)
Це те саме, але більш ідіоматично:
```suggestion
	var err error
```

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	}
Чому двічі викликається метод `SaveToServer`? Це ж юніт тест, як я зрозумів.

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +		t.Errorf("Error saving history to server with DetectMovement() Tiger")
Варто вивести `err`.

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +		t.Errorf("Error saving history to server with Move() Tiger")
Варто виводити, що очікувалось і що отримали. Стосується всіх тестів.

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	}()
Може для паніки окремий тест зробити?

Наприклад, за допомогою [`t.Run`](https://pkg.go.dev/testing#T.Run)

2024-09-02 10:34 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +		animalID  int
Чому використовується анонімна структура, якщо можна використати `HistoryItem`?

2024-09-04 15:48 UTC, alexandear requested changes

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	})
Здається, нам це зовсім не потрібно та можна видалити. Функція, судячи з назви, тестує `dayCamera.SaveToServer`.

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	var err error
Чи можемо обійтися без цього рядку?

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	var err error
Чи можемо обійтися без цього рядку?

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	}()
Здається, нам це зовсім не потрібно та можна видалити. Функція тестує `nightCamera.SaveToServer`.

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	err = nightCamera.SaveToServer(*history)
"*" зайва:
```suggestion
	err = nightCamera.SaveToServer(history)
```

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	history, err = tiger.camera.DetectMovement(direct, history, tiger.id)
Якщо змінити на ось так
```suggestion
	history, err := tiger.camera.DetectMovement(direct, history, tiger.id)
```
то можна видалити рядки `var history []HistoryItem` та `var err error`.

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	} else if history[0].direction != direct || history[0].animalID != tiger.id {
[`t.Fatalf`](https://pkg.go.dev/testing#T.Fatalf) припиняє виконання цього тесту при фейлі, тому краще використовувати цю функцію для спрощення тесту:
```suggestion
	if err != nil {
		t.Fatalf("Error saving history to server with DetectMovement() Tiger: %v", err)
	}
	if history[0].direction != direct || history[0].animalID != tiger.id {
```

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	} else if history[0].direction != direct || history[0].animalID != tiger.id {
Змінити для всіх тестів у файлі.

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main_test.go
> +	history, err = tiger.camera.DetectMovement(direct, history, tiger.id)
Спростити таким чином всі тести у файлі.

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +		}
Бажано покрити тестами `switch`:

<img width="772" alt="image" src="https://github.com/user-attachments/assets/6bcd6d61-7f61-43b8-bd70-019c0585f14f">

2024-09-04 15:48 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +}
В 5 вебінарі розглядалися робота з пакетами. Тому попрошу винести структури та методи для роботи з ними в окремий пакет `camera`. `Animal` можна винести в пакет `animal`.

Лише `type Camera interface` хай буде в цьому файлі.

2024-09-04 16:55 UTC, sarff commented on gocourse05/zooobservation/main_test.go
> +	})
Згоден, якась фігня. якщо буде паніка - тести і без цього впадуть

2024-09-04 17:59 UTC, sarff commented on gocourse05/zooobservation/main.go
> +}
якщо я залишаю interface - все ломається, тому перемістив його теж

2024-09-05 11:11 UTC, alexandear requested changes

2024-09-05 11:11 UTC, alexandear commented on gocourse05/webinar/main.go
> +	// fake panic
📝 суб'єктивно:
```suggestion
	// emulating possible panic
```

2024-09-05 11:11 UTC, alexandear commented on gocourse05/webinar/main.go
> +			return
Можна не переривати програму при виникненні помилки, тобто прибрати `return`.

Типу якщо є 100 картинок, то це нормально, що кілька штук не обробляться. Ми будемо знати про це через лог.

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/common/common.go
> +package common
`common` дуже рідко підходить як назва пакету, не рекомендую використовувати взагалі.

В блозі https://go.dev/blog/package-names є приклади поганих імен пакетів:

> Avoid meaningless package names. Packages named util, common, or misc provide clients with no sense of what the package contains. This makes it harder for clients to use the package and makes it harder for maintainers to keep the package focused. Over time, they accumulate dependencies that can make compilation significantly and unnecessarily slower, especially in large programs. And since such package names are generic, they are more likely to collide with other packages imported by client code, forcing clients to invent names to distinguish them.

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/common/common.go
> +package common
Здається, `Direction` можна перенести в пакет `camera`.

`HistoryItem` також в пакет `camera`. Думаю, можна перейменувати поле `AnimalID` в просто `ID`, щоб відв'язатися від `Animal`.

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/go.mod
> +module zooobservation
📝 здається, десь вже радив так називати модулі:
```suggestion
module github.com/sarff/prjctr-golang_beginning/gocourse05/zooobservation
```

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/animal/animal.go
> +	Id      int
https://go.dev/wiki/CodeReviewComments#initialisms
```suggestion
	ID      int
```

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/animal/animal.go
> +	Camera  camera.Camera
Трохи дивно, що звір містить в собі поле камери. Це ж не людина, в якої в рюкзаку є фотоапарат.

Якщо подумати логічно, то звір не може сам себе фотографувати. Фоткає хтось інший, в нашому випадку камера десь висить в будівлі та автоматично фотографує.
Тому треба ще придумати абстракцію, яка буде працювати з камерами та фоткатиме звіра.

Я не просто так коментую. Реалістичні програми легші для розуміння.

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/animal/animal_test.go
> +	}
Так легше читається:
```suggestion
	if err != nil {
		t.Fatalf("Unexpected error: got=%v, but want=<nil>", err)
	}
	if len(history) == 0 {
		t.Fatalf("Unexpected empty history")
	}
	if history[0].AnimalID != tiger.Id {
		t.Errorf("Wrong history animalID: got=%v, but want=%v", history[0].AnimalID, tiger.Id)
	}
	if history[0].Direction != direct {
		t.Errorf("Wrong direction: got=%v, but want=%v", history[0].Direction, direct)
	}
```

Чому:

1. Один if - одна перевірка.
2. Захистились від ситуації, коли `history[0]` панікує.
3. Немає if-else. Так, ця конструкція погіршує читабельність.
4. Може зламатись `AnimalID` або `direct` - тоді в лозі тесту буде дві помилки замість однієї.
5. Поправили меседжі згідно з рекомендаціями https://go.dev/wiki/CodeReviewComments#useful-test-failures. Трохи суб'єктивно

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/animal/animal_test.go
> +	direct := common.Left
`direct` та `direction` - це в загальному різні слова:
```suggestion
	direction := common.Left
```

https://www.merriam-webster.com/dictionary/direct
https://www.merriam-webster.com/dictionary/direction

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/animal/animal_test.go
> +	}
Пропоную редагувати схожим чином інші тести.

2024-09-05 11:11 UTC, alexandear commented on gocourse05/zooobservation/animal/animal_test.go
> +	history, err := tiger.Move(direct, historyItems)
Здається, так буде працювати:
```suggestion
	history, err := tiger.Move(direct, nil)
```

2024-09-05 11:13 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +/*
Пропоную також проапдейтити "description" в PR до актуального стану на зараз. Вже було багато перейменувань та змін.

2024-09-08 15:17 UTC, alexandear approved these changes
LGTM

Пофіксити коменти і можна мерджити.

2024-09-08 15:17 UTC, alexandear commented on gocourse05/zooobservation/camera/camera.go
> +	Time      time.Time
`Time` - занадто загальна назва для поля, можна уточнити:
```suggestion
	CreatedAt time.Time
```

2024-09-08 15:17 UTC, alexandear commented on gocourse05/zooobservation/camera/camera.go
> +}
Тут так і проситься конструктор та неекспортовані поля:
```suggestion
type Controller struct {
	dayCamera   DayCamera
	nightCamera NightCamera
}

func NewController() *Controller {
	return &Controller{
		dayCamera:   DayCamera{},
		nightCamera: NightCamera{},
	}
}
```

2024-09-08 15:17 UTC, alexandear commented on gocourse05/zooobservation/camera/camera.go
> +	camera = &c.NightCamera
Здається, так має працювати:
```suggestion
	camera := Camera(&c.nightCamera)
```

2024-09-08 15:17 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +		Species: "bear",
Для `"tiger"` та `"bear"` напевно краще додати константи і використовувати їх.

2024-09-08 15:17 UTC, alexandear commented on gocourse05/zooobservation/camera/camera.go
> +			prev = elem.Direction
Ця логіка не покрита юніт тестами:
<img width="756" alt="image" src="https://github.com/user-attachments/assets/5bee4ff3-142a-4244-9e5f-60642e98cfac">

2024-09-08 15:17 UTC, alexandear commented on gocourse05/zooobservation/main.go
> +
📝 зайвий рядок

2024-09-08 19:10 UTC, sarff commented on gocourse05/zooobservation/camera/camera.go
> +			prev = elem.Direction
<img width="958" alt="image" src="https://github.com/user-attachments/assets/abb615d4-cd6c-403b-9ea5-ff52511182b6">
100%

2024-09-08 19:16 UTC, merged