Hw06
sarff/prjctr-golang_beginning pull request #5
Opened 2024-08-29 07:55 UTC by sarff

- webinar
Виділив обʼєкт Oxygen і прогнав по функціям (серце, легені, судини) використовуючи канали і горутини

- generalSmartZoo
Використав WaitGroup, Створив три канали animalChan, enclosureChan, feederChan, які не взаємодіють один з одним і додав slog
Останній цикл не кидав в горутину, не встиг перевірити чи є в цьому сенс.

2024-08-30 17:37 UTC, alexandear requested changes

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/go.mod
https://github.com/sarff/prjctr-golang_beginning/pull/3#discussion_r1730330182

`generalSmartZoo` -> `smartzoo`.

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/go.mod
> +module generalSmartZoo
```suggestion
module github.com/sarff/prjctr-golang_beginning/gocourse06/smartzoo
```

https://github.com/sarff/prjctr-golang_beginning/pull/2#discussion_r1720995037

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +func controlCondition(animalChan chan *Animal, wg *sync.WaitGroup, log *slog.Logger) {
Варто додати стрілочку до каналу, оскільки ми з нього лише читаємо.

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +	}
📝 Можна трішки коротше та ефективніше:
```suggestion
	animals := make([]Animal, n)
	for i := range n {
		animals[i] = Animal{
			ID:     i,
			Health: rand.IntN(100),
			Hunger: rand.IntN(100),
			Mood:   rand.IntN(100),
		}
	}
```

Так для всіх генераторів.

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +		wg.Wait()
Навіщо нам цей `wg.Wait()` тут? Чи буде програма працювати, коли видалимо рядок?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +		wg.Wait()
Навіщо нам цей `wg.Wait()` тут? Чи буде програма працювати, коли видалимо рядок?

[WaitGroups - Part 1 (Concurrency in Go #2)
](https://youtu.be/srb6fbioEY4?si=ITMlAKUUjQom4DRB)

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +	go func() {
Для чого потрібна ця горутина?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +	go func() {
Для чого нам ця горутина?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main_test.go
> +	defer os.Remove(logFile.Name())
Можна поререфакторити за допомогою [`t.TempDir`](https://pkg.go.dev/testing#T.TempDir).

2024-08-30 17:37 UTC, alexandear commented on gocourse06/webinar/main.go
> +	defer close(heartChan)
А чи дійсно потрібно закривати канали `heartChan` та `lungsChan`?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/webinar/main.go
> +	defer close(lungsChan)
Мені здається, чи defer ніколи не виконається?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +	case animal, ok := <-animalChan:
Чи можемо обійтися тут без select-case?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +	case enclosure, ok := <-enclosureChan:
Чи можемо обійтися тут без select-case?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +	case feed, ok := <-feedChan:
Чи можемо обійтися тут без select-case?

2024-08-30 17:37 UTC, alexandear commented on gocourse06/generalSmartZoo/main.go
> +				log.Warn(fmt.Sprintf("Animal with ID %v - needs help", animal.ID))
Можна і треба обійтись без `fmt.Sprintf`.

В документації https://pkg.go.dev/log/slog#hdr-Attrs_and_Values є приклад, як виводити атрибути:

> ```
> slog.Info("hello", slog.Int("count", 3))
> ```

2024-08-30 17:37 UTC, alexandear commented on gocourse06/webinar/main.go
> +
```suggestion

```

2024-08-31 14:46 UTC, sarff commented on gocourse06/generalSmartZoo/main.go
> +	go func() {
щоб моніторинг відбувався одночасно (animals, enclosures, feeders)

2024-08-31 14:52 UTC, sarff commented on gocourse06/generalSmartZoo/main.go
> +	go func() {
10s проти 20s і вони незалежні

2024-08-31 15:22 UTC, sarff commented on gocourse06/generalSmartZoo/main.go
> +	go func() {
щоб моніторинг відбувався одночасно (animals, enclosures, feeders)

2024-08-31 15:22 UTC, sarff commented on gocourse06/generalSmartZoo/main.go
> +		wg.Wait()
буде, тому що у фунції є  defer wg

2024-08-31 15:23 UTC, sarff commented on gocourse06/generalSmartZoo/main.go
> +		wg.Wait()
буде, тому що у фунції є  defer wg

2024-08-31 17:05 UTC, sarff commented on gocourse06/webinar/main.go
> +	defer close(heartChan)
ні не треба, тому що ми робимо ось так? heartChan <- oxygen

2024-08-31 18:12 UTC, sarff commented on gocourse06/webinar/main.go
> +
тут немає тексту, що не так?

2024-09-03 09:33 UTC, alexandear requested changes

2024-09-03 09:33 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +			wg.Add(1)
`wg.Add` не може бути всередині горутини `go`. Це груба помилка.

Ось тут раджу почитати
https://leangaurav.medium.com/common-mistakes-when-using-golangs-sync-waitgroup-88188556ca54
та тут https://stackoverflow.com/questions/65213707/where-to-put-wg-add

2024-09-03 09:34 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +			wg.Add(1)
Пофіксити `wg.Add` в усіх місцях, не лише тут.

2024-09-03 09:34 UTC, alexandear commented on gocourse06/webinar/main.go
> +
Це ж зайвий рядок)

2024-09-03 09:35 UTC, alexandear commented on gocourse06/smartzoo/main_test.go
> +	// defer os.Remove(logFile.Name())
Закоментований код можна видалити.

2024-09-08 15:31 UTC, alexandear requested changes

2024-09-08 15:31 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +		}
📝 Те саме:
```suggestion
		isOpen := !enclosure.IsOpen
```

2024-09-08 15:31 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +	wg.Add(1)
Помилка.

Пропоную розібратися, чому не можна робити `wg.Add(1)` у цій функції. Ось тут детально розписано https://leangaurav.medium.com/common-mistakes-when-using-golangs-sync-waitgroup-88188556ca54

2024-09-08 15:31 UTC, alexandear commented on gocourse06/smartzoo/main_test.go
> +func TestControlCondition(t *testing.T) {
Тест не встигає завершитись за 60 секунд, запускав так:

```
❯ go test -race -timeout 60s ./...

panic: test timed out after 1m0s
        running tests:
                TestControlCondition (1m0s)

goroutine 8 [running]:
testing.(*M).startAlarm.func1()
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:2373 +0x1dc
created by time.goFunc
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/time/sleep.go:215 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00010a4e0, {0x102732625, 0x14}, 0x1027b7960)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1751 +0x600
testing.runTests.func1(0xc00010a4e0)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:2168 +0x84
testing.tRunner(0xc00010a4e0, 0xc00012fad8)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1690 +0x188
testing.runTests(0xc00000c048, {0x1028c6bc0, 0x1, 0x1}, {0xc000106360?, 0x102686540?, 0x1028d0740?})
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:2166 +0x6e4
testing.(*M).Run(0xc0001020a0)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:2034 +0xb78
main.main()
        _testmain.go:45 +0x114

goroutine 6 [semacquire]:
sync.runtime_Semacquire(0xc00000e2d8?)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/runtime/sema.go:71 +0x2c
sync.(*WaitGroup).Wait(0xc00000e2d0)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/sync/waitgroup.go:118 +0x78
github.com/sarff/prjctr-golang_beginning/gocourse06/smartzoo.TestControlCondition(0xc00010a680)
        /Users/Oleksandr_Redko/src/github.com/sarff/prjctr-golang_beginning/gocourse06/smartzoo/main_test.go:32 +0x23c
testing.tRunner(0xc00010a680, 0x1027b7960)
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1690 +0x188
created by testing.(*T).Run in goroutine 1
        /opt/homebrew/Cellar/go/1.23.0/libexec/src/testing/testing.go:1743 +0x5e4
FAIL    github.com/sarff/prjctr-golang_beginning/gocourse06/smartzoo    60.459s
FAIL
```

2024-09-18 08:09 UTC, sarff commented on gocourse06/smartzoo/main_test.go
> +func TestControlCondition(t *testing.T) {
go test -race -timeout 60s ./...
ok      github.com/sarff/prjctr-golang_beginning/gocourse06/smartzoo    2.212s

2024-09-18 16:06 UTC, alexandear approved these changes
LGTM

Пофіксити коменти і можна мерджити.

2024-09-18 16:06 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +func controlEnclosure(enclosureChan chan *Enclosure, isOpen bool, wg *sync.WaitGroup, log *slog.Logger) {
Канал лише для читання, тому можна так:
```suggestion
func controlEnclosure(enclosureChan <-chan *Enclosure, isOpen bool, wg *sync.WaitGroup, log *slog.Logger) {
```

2024-09-18 16:06 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +func loggerNew(writer *os.File) *slog.Logger {
Ось так має працювати, тому що `os.File` імплементує `io.Writer`:
```suggestion
func loggerNew(writer io.Writer) *slog.Logger {
```

Насправді, методу [`slog.NewJSONHandler`](https://pkg.go.dev/log/slog#NewJSONHandler) потрібен лише щось, що імплементує `io.Writer`:

```go
// NewJSONHandler creates a [JSONHandler] that writes to w,
// using the given options.
// If opts is nil, the default options are used.
func NewJSONHandler(w io.Writer, opts *HandlerOptions) *JSONHandler {
```

2024-09-18 16:06 UTC, alexandear commented on gocourse06/smartzoo/main_test.go
> +	}
Можна обійтися без тимчасового файлу, використовуючи [`bytes.Buffer`](https://pkg.go.dev/bytes#Buffer):

```go
func TestControlCondition(t *testing.T) {
	actualLog := &bytes.Buffer{}

	animalChan := make(chan *Animal, 1)
	wg := new(sync.WaitGroup)
	log := loggerNew(actualLog)

	animal := &Animal{
		ID:     1,
		Health: 25, // Рівень здоров'я нижче 30
		Hunger: 25, // Рівень голоду нижче 30
		Mood:   25, // Настрій нижче 30
	}
	wg.Add(1)
	go controlCondition(animalChan, wg, log)
	animalChan <- animal

	wg.Wait()
	close(animalChan)

	wantMessages := []string{
		"\"msg\":\"Animal needs help\",\"animalId\":1",
		"\"msg\":\"Animal needs to be fed\",\"animalId\":1",
		"\"msg\":\"Animal - needs to be released from the cage\",\"animalId\":1",
	}

	for _, message := range wantMessages {
		if !strings.Contains(actualLog.String(), message) {
			t.Errorf("Wanted testLog message '%s' not found", message)
		}
	}
}
```

Працюватиме, якщо змінити сигнатуру `loggerNew`:

```go
func loggerNew(writer io.Writer) *slog.Logger {
```

2024-09-18 16:06 UTC, alexandear commented on gocourse06/smartzoo/main.go
> +func loggerNew(writer *os.File) *slog.Logger {
Так більш канонічно:
```suggestion
func newLogger(writer io.Writer) *slog.Logger {
```

2024-10-09 18:53 UTC, merged