hw07
sarff/prjctr-golang_beginning pull request #6
Opened 2024-09-01 20:57 UTC by sarff

все як завжди: папка 
webinar - те що на вебінарі
birdaviary - домашка

в домашці не зрозумів як я маю при такій структурі вписувати в go mod повний шлях до github - воно перестаєе працювати, чия маю це робити вже на фінальному коміті перед мерджем в main? 

також не потягнув всю задачу - вона дуже важка, схоже що WG тут не треба було використовувати, а краще заюзати канали. 
Чи правильно використовувати slog як в моїй домашці? маю на увазі що я створю в main() - slog.new() - і потім де є логи закидую його у кожну функцію... щось мені здалось що це не ок, але по іншому в мене не вийшло

2024-09-03 16:23 UTC, alexandear requested changes

2024-09-03 16:23 UTC, alexandear commented on gocourse07/webinar/main.go
> +	if d == 1 {
Можемо використати константи замість `int` для підвищення читабельності?

```go
const (
	signalSit = iota
	signalDance
)

2024-09-03 16:23 UTC, alexandear commented on gocourse07/webinar/main.go
> +	if d == 1 {
Також може краще передавати в цю функцію канал?

2024-09-03 16:23 UTC, alexandear commented on gocourse07/webinar/main.go
> +	}()
А чи не зайва ця горутина?

Рекомендую почитати https://dou.ua/forums/topic/31777/ і відповісти на це запитання.

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/internal/storage/storage.go
> +	log  *logger.Logger
Є така ідіома, як "Mutex Hat" https://dmitri.shuralyov.com/idiomatic-go#mutex-hat:
```suggestion
	mu   sync.Mutex
	data map[string][]int

	log  *logger.Logger
```

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/go.mod
> +module birdaviary
Ось так же має працювати:
```suggestion
module github.com/sarff/prjctr-golang_beginning/gocourse07/birdaviary
```

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/internal/logger/log.go
> +func New(writer *os.File) *Logger {
Чи можемо обійтися без `*os.File` та використати інтерфейс?

Підказка: глянути на параметри [`slog.NewJSONHandler`](https://pkg.go.dev/log/slog#NewJSONHandler).

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/internal/storage/storage.go
> +	m.data[sensorName] = append(m.data[sensorName], value)
А хіба потрібно захищати мютексом `m.log`?
```suggestion
	m.mu.Lock()
	m.data[sensorName] = append(m.data[sensorName], value)
	m.mu.Unlock()
```

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/internal/centralsystem/centralsystem.go
> +	Memory *storage.Storage
Зробімо всі поля приватними:
```suggestion
	memory *storage.Storage
```

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/cmd/app/main.go
> +			wg.Add(1)
Ось тут та сама помилка, про яку писав
https://github.com/sarff/prjctr-golang_beginning/pull/5#discussion_r1741745516

2024-09-03 16:23 UTC, alexandear commented on gocourse07/birdaviary/cmd/app/main.go
> +		return
Пропоную залогувати `err`.

2024-09-07 19:33 UTC, sarff commented on gocourse07/birdaviary/internal/logger/log.go
> +func New(writer *os.File) *Logger {
якщо мається на увазі io.Writer - тоді зробив, якщо ні... не зрозумів що маю зробити

2024-09-18 16:39 UTC, alexandear requested changes

2024-09-18 16:39 UTC, alexandear commented on gocourse07/webinar/main.go
> +	// wg := new(sync.WaitGroup)
Закоментований код?

2024-09-18 16:39 UTC, alexandear commented on gocourse07/webinar/main.go
> +func dancing(d int) {
Ось так ми підвищуємо читабельність та гарантуємо, що функція `dancing` прийматиме лише `signalSit` чи `signalDance`:
```suggestion
type signal int

const (
	signalSit signal = iota
	signalDance
)

func dancing(d signal) {
```

2024-09-18 16:39 UTC, alexandear commented on gocourse07/webinar/main.go
> +func dancing(d int) {
Чому параметр називається `d`? Думаю має бути `s`, від `signal`.

2024-09-18 16:39 UTC, alexandear commented on gocourse07/webinar/main.go
> +	signals := [10]int{1, 1, 0, 0, 1, 1, 1, 1, 0, 0} // 1 - танцюємо, 0 сидимо
Замість `0` має бути `signalSit`, замість `1` - `signalDance`. Інакше, навіщо нам константи?

2024-09-18 16:39 UTC, alexandear commented on gocourse07/webinar/main.go
> +	go func(signals [10]int) {
Працюватиме і так:
```suggestion
	go func() {
```

2024-09-18 16:39 UTC, alexandear commented on gocourse07/webinar/main.go
> +	}
Тут ідеально лягає концепція закривання каналу `legsChan`:
```suggestion
		for _, signal := range signals {
			legsChan <- signal
			time.Sleep(1 * time.Second)
		}
		close(legsChan)
	}()

	for s := range legsChan {
		dancing(s)
	}
```

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/cmd/app/main.go
Можна без директорії `app`, вона зайва.

Просто `cmd/main.go`.

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/cmd/app/main.go
> +		go brightnessSensor.Start(wg)
В програмі є 3 сенсори: `tempSensor`, `humiditySensor`, `brightnessSensor`. Ось цей код викликає метод `.Start()` на кожному з цих сенсорів 24 рази. Здається, тут щось не те.

По логіці, метод `.Start()` для кожного сенсора має викликатися лише один раз. В майбутньому, може додатися метод `.Stop()`.

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/internal/centralsystem/centralsystem.go
> +func (c *CentralSystem) Stop() {
Ось цей метод ніде не викликається. Чому?

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/internal/logger/log.go
> +	return log
Можна спростити
```suggestion
	return &Logger{
		Logger: slog.New(slog.NewJSONHandler(writer, nil)),
	}
```

`slog.SetDefault` не потрібен, тому що програма не використовує `slog.Info`, `slog.Warn` і т.д.

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/internal/sensor/sensor.go
> +}
Цей інтерфейс ніде не використовується, для чого програмі він? Якщо видалю, програма запускається, тести проходять.

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/internal/sensor/sensor.go
> +}
Стоп, а де тести? Дописати.

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/internal/sensor/sensor.go
> +func (s *MainSensor) GenerateSensorData() int {
Може зробити цю функцію приватною?

2024-09-18 16:39 UTC, alexandear commented on gocourse07/birdaviary/internal/sensor/sensor.go
> +	s.log.Info("Starting sensor ", "sensor", s.name)
Зайвий пробіл:
```suggestion
	s.log.Info("Starting sensor", "sensor", s.name)
```

2024-10-05 07:48 UTC, alexandear approved these changes
LGTM

2024-10-05 07:48 UTC, alexandear commented on gocourse07/birdaviary/cmd/main.go
> +	brightnessSensor = sensor.NewSensor(cs, log, "BrightnessSensor")
В конкретній імплементації немає якогось бенефіту в використанні інтерфейса `sensor.Sensor`. Значно простіше та менше коду ось так: 
```suggestion
	tempSensor := sensor.NewSensor(cs, log, "TemperatureSensor")
	humiditySensor := sensor.NewSensor(cs, log, "HumiditySensor")
	brightnessSensor := sensor.NewSensor(cs, log, "BrightnessSensor")
```

2024-10-05 07:48 UTC, alexandear commented on gocourse07/birdaviary/cmd/main.go
> +	brightnessSensor = sensor.NewSensor(cs, log, "BrightnessSensor")
Бенефіт був би, якщо задекларувати колекцію сенсорів та працювати з ними однаково:

```go
	sensors := []sensor.Sensor{
		sensor.NewTemperatureSensor(cs, log),
		sensor.NewHumiditySensor(cs, log),
		sensor.NewBrightnessSensor(cs, log),
	}
	wg.Add(len(sensors))

	for _, s := range sensors {
		go s.Start(wg)
	}
```

2024-10-05 07:48 UTC, alexandear commented on gocourse07/birdaviary/internal/sensor/sensor.go
> +func (s *MainSensor) Stop(wg *sync.WaitGroup) {
Що буде, як клієнт викличе цей метод два рази? Може зробити його приватним?

2024-10-05 11:35 UTC, merged