Hw08
sarff/prjctr-golang_beginning pull request #7
Opened 2024-09-08 21:36 UTC by sarff

Папка webinar - PtrOf, FindIn, Unique

Папка collartask: 
Створив два пакети animal, в якому додав інтерфейс Animal

та collar 

почав писати, бачу деякі помилки... треба виправити

2024-09-10 10:53 UTC, alexandear requested changes

2024-09-10 10:53 UTC, alexandear commented on gocourse11/webinar/main.go
> +package main
Здається, зайвий файл. Можеш видалити з цього PR?

2024-09-10 10:53 UTC, alexandear commented on gocourse08/webinar/main.go
> +func PtrOf[T int | float64](v T) *T {
Адресу можна взяти з будь-якого типу:

```suggestion
func PtrOf[T any](v T) *T {
```

Глянути імплементацію реального коду можна тут:
https://github.com/dapr/kit/blob/v0.13.2/ptr/of.go#L21

2024-09-10 10:53 UTC, alexandear commented on gocourse08/webinar/main.go
> +	array := make(map[T]struct{})
Можна трішки покращити назви:
```suggestion
	set := make(map[T]struct{})
```

2024-09-10 10:53 UTC, alexandear commented on gocourse08/webinar/main.go
> +	uniqueSlice := make([]T, 0, len(array))
```suggestion
	unique := make([]T, 0, len(set))
```

2024-09-10 10:53 UTC, alexandear commented on gocourse08/webinar/main.go
> +func FindIn[T comparable](sl []T, find T) int {
Можна параметри назвати, як тут https://pkg.go.dev/slices#BinarySearch:
```suggestion
func FindIn[T comparable](s []T, target T) int {
```

2024-09-10 10:53 UTC, alexandear commented on gocourse08/webinar/main.go
> +func Unique[T comparable](sl []T) []T {
Можна покращити назву параметру, як ось тут https://pkg.go.dev/slices#Compact:
```suggestion
func Unique[T comparable](s []T) []T {
```

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/main.go
> +	newAnimal := animal.NewAnimal()
Краще дозволити клієнтському коду вибирати тварину для створення. Це зменшує coupling та збільшує перевикористання пакету `animal`.

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/main.go
> +	newAnimal := animal.NewAnimal()
Наприклад, нехай ми хочемо спочатку створити тигра:
```go
tiger := animal.New(tigerPulse, tigerTemperature)
```

Далі одягаємо на тигра нашийник:
```go
collar := colar.NewColar()
tiger.WearCollar(collar) // чи collar.PutOn(tiger)
```

Потім йде логіка вимірювання та надсилання даних по GPRS.

На другий день цей же ошийник одягаємо на ведмедя:

```go
bear := animal.New(bearPulse, bearTemperature)
bear.WearCollar(collar) // чи collar.PutOn(bear)
```

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/collar/collar.go
> +	mu := sync.Mutex{}
Здається, цей мютекс не потрібен. Що буде, якщо його видалити?

Якщо мютекс потрібен, то краще зробити його полем в структурі `Collar`.

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +}
Звір може лише дихати та видавати звуки. Він не може записувати своє дихання та звуки. Записують саме датчики, які містяться в ошийнику.

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +}
Коли програма реальна, то вона легше читається.

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +	Sounding    []T
Це ж слайси, значить закінчення `s`:
```suggestion
	Breaths   []T
	Sounds    []T
```

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/main.go
> +func main() {
Програма з data race, треба підфіксити. Запускати з `-race` флажком, про який почитати тут https://go.dev/doc/articles/race_detector

<details>
<summary>Вивід</summary>

```
❯ go run -race .
The collar is initialized to:  tiger
Saved to server storage: 
Breathing --> [20.088629268318382] 
Sounding --> [36.6138125134029] 
==================
WARNING: DATA RACE
Write at 0x00c00012e018 by main goroutine:
  github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/collar.(*Collar).SetStrategy()
      /Users/Oleksandr_Redko/src/github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/collar/collar.go:32 +0x25c
  main.main()
      /Users/Oleksandr_Redko/src/github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/main.go:30 +0x258

Previous read at 0x00c00012e018 by goroutine 6:
  github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/collar.(*Collar).ProcessData()
      /Users/Oleksandr_Redko/src/github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/collar/collar.go:43 +0xe0
  main.main.gowrap1()
      /Users/Oleksandr_Redko/src/github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/main.go:36 +0x34

Goroutine 6 (running) created at:
  main.main()
      /Users/Oleksandr_Redko/src/github.com/sarff/prjctr-golang_beginning/gocourse08/collartask/main.go:36 +0x1fc
==================
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585] 
Sounding --> [36.6138125134029 52.80341558625672] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346 37.608717232732694] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398 52.8931933545807] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346 37.608717232732694 11.616714138917727 10.059289932356352] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398 52.8931933545807 88.02001822661164 96.10204055019102] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668] 
Saved to local storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346 37.608717232732694 11.616714138917727] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398 52.8931933545807 88.02001822661164] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346 37.608717232732694 11.616714138917727 10.059289932356352 27.98991489723455 16.320012449760334] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398 52.8931933545807 88.02001822661164 96.10204055019102 85.05019760534208 24.21898190889744] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346 37.608717232732694 11.616714138917727 10.059289932356352 27.98991489723455 16.320012449760334 24.609321674418915 47.96827906449054 10.540004044437746 31.852802273433134] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398 52.8931933545807 88.02001822661164 96.10204055019102 85.05019760534208 24.21898190889744 19.30845255150674 86.09428385128858 45.85921848171446 50.1432066699357] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64.45583611758578 88.79075977863009 36.7020561332263 88.7918428475844 39.7013382841331 57.828278257749346 37.608717232732694 11.616714138917727 10.059289932356352 27.98991489723455] 
Sounding --> [36.6138125134029 52.80341558625672 95.63890610105891 79.3253034707456 52.87066716551184 13.83836740442156 1.8894743203302977 47.15717896052563 83.51641849619102 19.529849647273668 58.21401546536398 52.8931933545807 88.02001822661164 96.10204055019102 85.05019760534208] 
Saved to server storage: 
Breathing --> [20.088629268318382 0.2099874948535585 97.02236858846328 26.46673949299201 64.68309945247371 64 [...]

2024-09-10 10:53 UTC, alexandear commented on gocourse08/collartask/main.go
> +func main() {
Опціонально.

Хочеться бачити, як працював GPRS сигнал залежно від часу, як і в який момент генерувались дані від датчиків.

Наприклад, по логам буде видно, що з 12:02 до 12:10 не було сигналу GPRC. За ці 8 хвилин згенерувались такі-то дані з датчиків. Далі з'явився GPRC та за кілька секунд дані передались.

2024-09-15 08:07 UTC, sarff commented on gocourse08/collartask/main.go
> +	newAnimal := animal.NewAnimal()
змінну залишив як collarDevice, тому що підкреслює мені як зауваження що не можна називати змінну так само як пакет (collar)

2024-09-15 11:26 UTC, sarff commented on gocourse08/collartask/main.go
> +	newAnimal := animal.NewAnimal()
і зробив так collarDevice.WearCollar(bear) - наче логічніше так як головний обʼєкт у нас collarDevice

2024-09-15 11:58 UTC, sarff commented on gocourse08/collartask/main.go
> +func main() {
<img width="703" alt="image" src="https://github.com/user-attachments/assets/42195f31-213c-47e0-9c49-3d8b7d913c92">
додав mutex

2024-09-15 11:59 UTC, sarff commented on gocourse08/collartask/main.go
> +func main() {
так, теж про це думав... але не маю часу з роботою. Опціонально залишу після курсів на доробку)

2024-09-15 17:17 UTC, alexandear approved these changes
LGTM

Пофіксити коменти і можна мерджити.

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +//}
Закоментований код. Здається, забув видалити.

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +type DataAnimal[T float64] struct {
Чи можемо зробити так, щоб працювала конструкція `DataAnimal[float32]`? Зараз працює лише `DataAnimal[float64]`

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +func New(animalPulse int, animalTemperature float64, animalType AnimalType) DataAnimal[float64] {
Простіше:
```suggestion
func New(pulse int, temperature float64, animalType AnimalType) DataAnimal[float64] {
```

З `animalType` не вийде змінити на `type`, тому хай буде так.

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/animal/animal_test.go
> +}
Мапа `validAnimals` лише ускладнює тест. Можна ж просто:
```go
func TestNewAnimal(t *testing.T) {
	pulse := rand.IntN(100)
	temperature := rand.Float64()
	animal := New(pulse, temperature, Tiger)
	expected := DataAnimal[float64]{
		AnimalType:  string(Tiger),
		Pulse:       pulse,
		Temperature: temperature,
		Breaths:     []float64{},
		Sounds:      []float64{},
	}

	if !reflect.DeepEqual(expected, animal) {
		t.Errorf("Unexpected animal: got %v, but want %v", animal, expected)
	}
}
```

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/animal/animal.go
> +	AnimalType  string
`AnimalType` має мати тип `AnimalType` замість `string`:
```suggestion
	AnimalType  AnimalType
```

Так більш типобезпечно.

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/collar/collar.go
> +	mu           sync.RWMutex
Напевно, тут `Mutex Hat` застосовується https://dmitri.shuralyov.com/idiomatic-go#mutex-hat

2024-09-15 17:17 UTC, alexandear commented on gocourse08/collartask/collar/collar.go
> +}
Простіше:
```suggestion
func (c *Collar) Save(a animal.DataAnimal[float64]) {
	c.dataChan <- a
}
```

2024-09-22 19:02 UTC, sarff commented on gocourse08/collartask/animal/animal_test.go
> +}
мені так подобається)

2024-09-22 19:04 UTC, merged