hw09
sarff/prjctr-golang_beginning pull request #8
Opened 2024-09-17 21:22 UTC by sarff

/webinar:
 Створюємо обʼєкт patient1 (не можемо назвати patient так як є імпортований модуль)
 Обʼєкт контроль ліків drugControl
 Обʼєкт крапильниці dropperForPatient (приймає patient1 і drugControl)
 Далі функція React() - яка змішує потрібні ліки

/smartfeader:
В main рандомно заповнюю запаси кормушки і створюю кормушку feederMain з складом. Далі встановлюю зону (типу дивлюсь які в зоні звірі) і вивожу тих кого знайшов. Далі кормушка вираховує стратегію для звіра котрого знайшла, і кількість для звіра (декоратор) - основна функція розрахунку у feeder - FeedAnimals. + створив трохи тестів - використавши t.Run - зручно

2024-09-18 17:12 UTC, alexandear requested changes

2024-09-18 17:12 UTC, alexandear commented on gocourse09/webinar/main.go
> +	patient1 := &patient.Patient{}
> не можемо назвати patient так як є імпортований модуль

Можемо, спробуй:

```suggestion
	patient := &patient.Patient{}
```

Програма компілюється та працює.

В кожного пацієнта є ім'я. Можна на ім'я його назвати:

```go
john := &patient.Patient{}
```

2024-09-18 17:12 UTC, alexandear commented on gocourse09/.keep
Цей файл не потрібен.

Для чого .gitkeep, можна почитати тут https://www.freecodecamp.org/news/what-is-gitkeep/

2024-09-18 17:12 UTC, alexandear commented on gocourse09/smartfeeder/main.go
> +	zoneSetUp := zone.Zone{AnimalsInZone: make([]animal.Animal, 0)}.CheckZone()
Неочевидно, що функція `CheckZone` додає якихось звірів.

Що очікується:

```go
	animals := []animal.Animal{
		{Type: animal.Tiger, Count: 3},
		{Type: animal.Cow, Count: 2},
		{Type: animal.Bear, Count: 2},
		{Type: animal.Panda, Count: 22},
	}
	zone := zone.New()
	zone.AddAnimals()
```
або
```go
	zone := zone.New(animals)
```

2024-09-18 17:12 UTC, alexandear commented on gocourse09/smartfeeder/animal/animal.go
> +	Count int
Я відкрив цей файл, читаю зверху-донизу. І мені не дуже зрозуміло, що означає це поле `Count`. Треба або перейменувати зрозуміліше поле, або хоча б додати якийсь коментар.

2024-09-18 17:12 UTC, alexandear commented on gocourse09/smartfeeder/feeder/feeder.go
> +	GeneralFooD TypeFood = "General Food"
```suggestion
	GeneralFood TypeFood = "General Food"
```

2024-09-18 17:12 UTC, alexandear commented on gocourse09/smartfeeder/feeder/feeder.go
> +		foodNeeded := f.calculateFood(beast) // Decorator
А для чого коменти `// Strategy` та `// Decorator`? Це ж домашка по SOLID.

Здається, це зовсім не декоратор.

2024-10-12 20:47 UTC, sarff commented on gocourse09/webinar/main.go
> +	patient1 := &patient.Patient{}
можемо, але маю ось таке попередження 
<img width="533" alt="image" src="https://github.com/user-attachments/assets/3e801b9e-3950-47b4-9910-cd5272dc2a4b">

2024-10-14 10:34 UTC, alexandear approved these changes
LGTM

Не забувай оновлювати опис пул реквесту, коли змінюєш код.

2024-10-14 10:47 UTC, merged